config/routes.rb
Rails.application.routes.draw do
  

  resources :posts 
  devise_for :users
  resources :users
  root "posts#index"
resources :post do
  member do
    put "like", to: "posts#upvote"
    put "dislike", to: "posts#downvote"
  end
end

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	acts_as_punchable
	acts_as_votable
	has_attached_file :image, :styles => { :medium => "100x100>", :thumb => "300x300>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
         :validatable, :authentication_keys => [:login]

  validates :username,
  :presence => true,
  :uniqueness => {
    :case_sensitive => false
  }

  has_many :posts
  acts_as_voter
  validate :validate_username

def validate_username
  if User.where(email: username).exists?
    errors.add(:username, :invalid)
  end
end

  def self.find_first_by_auth_conditions(warden_conditions)
  conditions = warden_conditions.dup
  if login = conditions.delete(:login)
    where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
  else
    if conditions[:username].nil?
      where(conditions).first
    else
      where(username: conditions[:username]).first
    end
  end
end

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password, :twitter, :instagram, :facebook, :youtube, :about) }

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /posts
  # GET /posts.json
  def index
     if params[:sort_param] == "views"
      @posts = Post.sort_by_popularity('DESC')

      elsif params[:sort_param] == "likes"
      @posts = Post.all.order(:cached_votes_up => :desc)

      else
        @posts = Post.all.order("created_at DESC")
    end
  end

  def show
    @post.punch(request)
  end

  def new
    @post = current_user.posts.build
  end

  def edit
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url
  end

  def upvote
      @post = Post.find_by(id: params[:id])
      @post.liked_by current_user
      redirect_to @post
  end

  def downvote
      @post = Post.find_by(id: params[:id])
      @post.downvote_from current_user
      redirect_to @post
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find_by(id: params[:id])
    end

    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to posts_path, notice: "Not authorized to edit this post" if @post.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:description, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  	@user = User.find(params[:id])
  	@user_posts = @user.posts
  	@user_posts = Post.all.order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="nav-top">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <br>
      </br>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "EVC", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'Most like', posts_path(:sort_param => 'likes')%></li>
      <li><%= link_to 'Most views', posts_path(:sort_param => 'views')%></li>

      <% if user_signed_in? %>
          <li><%= link_to 'Upload', new_post_path %></li>
          <li><%= link_to "Profile", user_path(current_user) %></li>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>
    </ul>

  </div><!-- /.navbar-collapse -->

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Evc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<%= render 'layouts/header' %>
<div class="container-fluid">
          <%= yield %>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this postfrom being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div class="container">
<div id="profuploads">
<div id="posts" class="transitions-enabled">
  <% @posts.each do |post| %>
    <div class="box">
      <%= link_to image_tag(post.image.url(:medium)), post %>
      
    </div>
  <% end %>
</div>
</div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <%= image_tag @post.image.url(:medium) %>
      </div>
      <div class="panel-body">
        
        <p><strong><%= link_to(@post.user.username.capitalize, user_path(@post.user.id)) if @post.user %></strong></p>
        <p><%= @post.description %></p>
        
        <div class="votes">
          <strong>VIEWS</strong>
        <%= @post.hits %>
          <div class="votes">
          <%= link_to like_post_path(@post), class: "like", method: :put do%>
            <button type="button" class="btn btn-info" aria-label="Left Align">
              <span class="glyphicon glyphicon-thumbs-up glyphicon-align-center" aria-hidden="true"></span>
              <span class="badge"><%= @post.get_upvotes.size %></span>
              </button>
              <%end%>

              <%= link_to dislike_post_path(@post), class: "like", method: :put do%>
            <button type="button" class="btn btn-info" aria-label="Left Align">
              <span class="glyphicon glyphicon-thumbs-down glyphicon-align-center" aria-hidden="true"></span>
              <span class="badge"><%= @post.get_downvotes.size %></span>
              </button>
              <%end%>
              </div>
        <% if @post.user == current_user %>
         <%= link_to 'Edit', edit_post_path(@post) %>
        <% end %>

      </div>
    </div>
  </div>
</div>
<%= link_to  posts_path do %>
<span class="glyphicon glyphicon-arrow-left"></span>
<% end %>

app/views/users/show.html.erb
<div id="profheader">
	<h1><%= @user.username.capitalize %></h1>
		<ul id="prolinks">
				<li><%= link_to @user.youtube do %>
    <%= image_tag 'youtube.png', width: 50, height: 50%>
<% end %></li>
				<li><%= link_to @user.facebook do %>
    <%= image_tag 'facebook.png', width: 50, height: 50%>
<% end %></li>
				<li><%= link_to @user.twitter do %>
    <%= image_tag 'twitter.png', width: 50, height: 50%>
<% end %></li>
				<li><%= link_to @user.instagram do %>
    <%= image_tag 'instagram.jpg', width: 50, height: 50%>
<% end %></li>
	</ul>
</div>
</br>
<div id="profinfo">
	<h3>About</h3>
  <hr> <br>
		<p><%= @user.about %></p>
</div>

<div id="profuploads">
	<h3>Uploads</h3>
      <div id="posts" class="transitions-enabled">
<% @user_posts.each do |post| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(post.image.url(:medium)), post %>
      <div class="panel-body">
      <strong><%= post.user.username if post.user %></strong><br/>
        <%= post.description %><br/>
        <% if post.user == current_user %>
          <div class="actions">
            <%= link_to 'Edit', edit_post_path(post) %>
            <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
		</div>
	